<template>
  <div class="main-content">
    <breadcumb page="Registro de mensajes" folder="WhatsApp" />
    <b-card>
      <b-row class="mb-3"><b-col md="4" class="mb-2"><b-form-input v-model="search" placeholder="Buscar destinatario o mensaje" @keyup.enter="fetchLogs(1)" /></b-col><b-col md="3" class="mb-2"><b-form-select v-model="statusFilter" :options="statusOptions" @change="fetchLogs(1)" /></b-col><b-col md="5" class="mb-2 text-right"><b-button variant="primary" @click="fetchLogs(1)"><lucide-icon name="refresh-cw" /> Actualizar</b-button></b-col></b-row>
      <div v-if="isLoading" class="loading_page spinner spinner-primary mr-3"></div>
      <vue-good-table v-if="!isLoading" mode="remote" :columns="columns" :totalRows="totalRows" :rows="logs" :pagination-options="{ enabled: true, mode: 'records', perPage: perPage }" @on-page-change="onPageChange" @on-per-page-change="onPerPageChange" styleClass="table-hover tableOne vgt-table">
        <template slot="table-row" slot-scope="props"><span v-if="props.column.field === 'status'"><b-badge :variant="statusVariant(props.row.status)">{{ statusLabel(props.row.status) }}</b-badge></span><span v-else-if="props.column.field === 'error'"><span v-if="props.row.error" class="text-danger" :title="props.row.error">{{ truncate(props.row.error) }}</span><span v-else>—</span></span><span v-else-if="props.column.field === 'actions'"><b-button size="sm" variant="outline-danger" @click="remove(props.row.id)"><lucide-icon name="trash-2" /></b-button></span><span v-else>{{ props.formattedRow[props.column.field] }}</span></template>
      </vue-good-table>
    </b-card>
  </div>
</template>
<script>export default{data(){return{logs:[],totalRows:0,isLoading:true,perPage:15,currentPage:1,search:'',statusFilter:'',statusOptions:[{value:'',text:'Todos los estados'},{value:'pending',text:'Pendiente'},{value:'sent',text:'Enviado'},{value:'delivered',text:'Entregado'},{value:'read',text:'Leído'},{value:'failed',text:'Fallido'}],columns:[{label:'Destinatario',field:'recipient'},{label:'Tipo',field:'message_type'},{label:'Plantilla',field:'template_key'},{label:'Mensaje',field:'body'},{label:'Estado',field:'status'},{label:'Error',field:'error'},{label:'Enviado el',field:'sent_at'},{label:'Acciones',field:'actions',sortable:false}]}},mounted(){this.fetchLogs()},methods:{makeToast(variant,msg,title){this.$root.$bvToast.toast(msg,{title,variant,solid:true})},truncate(s){s=String(s||'');return s.length>40?s.slice(0,40)+'…':s},statusVariant(status){return{sent:'info',delivered:'primary',read:'success',failed:'danger',pending:'secondary'}[status]||'secondary'},statusLabel(status){return{sent:'Enviado',delivered:'Entregado',read:'Leído',failed:'Fallido',pending:'Pendiente'}[status]||status},fetchLogs(page=1){this.currentPage=page;this.isLoading=true;axios.get('/whatsapp/logs',{params:{page,per_page:this.perPage,search:this.search,status:this.statusFilter}}).then(res=>{this.logs=res.data.logs;this.totalRows=res.data.total}).catch(()=>this.makeToast('danger','No se pudieron cargar los registros.','Error')).finally(()=>this.isLoading=false)},remove(id){axios.delete('/whatsapp/logs/'+id).then(()=>{this.makeToast('success','Registro eliminado.','Éxito');this.fetchLogs(this.currentPage)}).catch(()=>this.makeToast('danger','No se pudo eliminar.','Error'))},onPageChange(params){this.fetchLogs(params.currentPage)},onPerPageChange(params){this.perPage=params.currentPerPage;this.fetchLogs(1)}}}</script>