<?php

declare(strict_types=1);

use App\Models\Central\LandingPrivacyPolicy;
use App\Models\Central\LandingRefundPolicy;
use App\Models\Central\LandingTermsConditions;
use Illuminate\Database\Migrations\Migration;

/**
 * Seeds (or, on a re-run, upserts) the comprehensive Spanish (base column)
 * and English (translations->en) content of the three public legal
 * documents. This runs as a migration — not a Seeder — because
 * LandingPageController's public actions abort(404) when the row simply
 * does not exist yet (LandingPrivacyPolicy::first()/LandingTermsConditions::
 * first()/LandingRefundPolicy::first() with no firstOrCreate() fallback on
 * the public path), so the page must never go live without this content
 * already present.
 *
 * Idempotent: safe to run multiple times. An admin who has since edited a
 * field through Super Admin -> CMS keeps their edit; this migration only
 * fills fields that are still empty, using updateOrCreate + a "only fill
 * blanks" pass rather than blindly overwriting.
 */
return new class extends Migration
{
    public function up(): void
    {
        $this->seed(LandingTermsConditions::class, $this->termsContent());
        $this->seed(LandingPrivacyPolicy::class, $this->privacyContent());
        $this->seed(LandingRefundPolicy::class, $this->refundContent());
    }

    public function down(): void
    {
        // Intentionally a no-op: this migration only seeds/backfills content
        // on existing single-row CMS tables. Rolling it back must not delete
        // legal content an admin may have since edited live.
    }

    /**
     * @param class-string $modelClass
     * @param array<string, array{es: string, en: string}> $fields
     */
    private function seed(string $modelClass, array $fields): void
    {
        /** @var \Illuminate\Database\Eloquent\Model $row */
        $row = $modelClass::first();

        $attributes = [];
        $translationsChanged = false;
        $translations = $row?->getRawOriginal('translations');
        $translations = is_string($translations) ? (json_decode($translations, true) ?: []) : ($translations ?: []);

        foreach ($fields as $field => $copy) {
            $currentBase = $row?->getRawOriginal($field);
            if ($currentBase === null || trim((string) $currentBase) === '') {
                $attributes[$field] = $copy['es'];
            }

            $currentEn = $translations['en'][$field] ?? null;
            if ($currentEn === null || trim((string) $currentEn) === '') {
                $translations['en'][$field] = $copy['en'];
                $translationsChanged = true;
            }
        }

        if ($translationsChanged) {
            $attributes['translations'] = $translations;
        }

        if (! $row) {
            $attributes['is_active'] = true;
            $attributes['last_updated'] = now()->toDateString();
            $modelClass::create($attributes);

            return;
        }

        if (! empty($attributes)) {
            $row->forceFill($attributes)->save();
        }
    }

    private function termsContent(): array
    {
        return [
            'acceptance' => [
                'es' => "Al crear una Cuenta, acceder al Servicio o hacer clic en \"Acepto\" durante el registro, celebras un contrato vinculante con PRODEX y aceptas quedar sujeto a estos Términos y Condiciones, a la Política de Privacidad y a la Política de Reembolsos y Cancelaciones, los cuales se incorporan por referencia. Si no estás de acuerdo con estos Términos, no debes crear una Cuenta ni utilizar el Servicio.\n\nSi contratas el Servicio en nombre de una empresa u otra entidad, estos Términos también vinculan a dicha entidad, y garantizas contar con la autoridad para ello conforme a la sección 4.\n\nPara determinadas Suscripciones, el pago se procesa a través de Paddle.com Market Limited en su calidad de comerciante registrado (Merchant of Record). Al completar dicho checkout, adicionalmente aceptas los términos de comprador de Paddle aplicables a esa transacción de pago, sin que ello sustituya tu aceptación de estos Términos respecto del uso del Servicio.",
                'en' => "By creating an Account, accessing the Service, or clicking \"I Agree\" during registration, you enter into a binding contract with PRODEX and agree to be bound by these Terms of Service, the Privacy Policy, and the Refund & Cancellation Policy, each of which is incorporated by reference. If you do not agree to these Terms, you must not create an Account or use the Service.\n\nIf you contract the Service on behalf of a company or other entity, these Terms also bind that entity, and you warrant that you have the authority to do so under Section 4.\n\nFor certain Subscriptions, payment is processed through Paddle.com Market Limited in its capacity as Merchant of Record. By completing that checkout, you additionally accept Paddle's buyer terms applicable to that payment transaction, without this replacing your acceptance of these Terms regarding use of the Service.",
            ],
            'use_license' => [
                'es' => "Sujeto al cumplimiento de estos Términos y al pago de las cuotas aplicables, PRODEX te otorga una licencia limitada, no exclusiva, intransferible y revocable para acceder y utilizar el Servicio únicamente para la operación interna de tu propio negocio, durante la vigencia de tu Suscripción.\n\nEsta licencia no incluye el derecho a: (a) revender, sublicenciar, arrendar o distribuir el Servicio a terceros no autorizados; (b) copiar, modificar o crear obras derivadas del software, salvo lo estrictamente permitido por la ley aplicable pese a esta restricción contractual; (c) realizar ingeniería inversa, descompilar o desensamblar el software, salvo en la medida en que la legislación aplicable prohíba expresamente esta restricción; o (d) eliminar avisos de propiedad intelectual del Servicio.\n\nTodos los derechos no otorgados expresamente en esta licencia quedan reservados a PRODEX.",
                'en' => "Subject to your compliance with these Terms and payment of applicable fees, PRODEX grants you a limited, non-exclusive, non-transferable, revocable license to access and use the Service solely for the internal operation of your own business, for the duration of your Subscription.\n\nThis license does not include the right to: (a) resell, sublicense, lease, or distribute the Service to unauthorized third parties; (b) copy, modify, or create derivative works of the software, except to the extent strictly permitted by applicable law notwithstanding this contractual restriction; (c) reverse-engineer, decompile, or disassemble the software, except to the extent applicable law expressly prohibits this restriction; or (d) remove intellectual-property notices from the Service.\n\nAll rights not expressly granted in this license are reserved to PRODEX.",
            ],
            'user_accounts' => [
                'es' => "Debes proporcionar información veraz, completa y actualizada al crear tu Cuenta, y mantenerla actualizada mientras la utilices. Eres responsable de mantener la confidencialidad de tus credenciales de acceso (usuario y contraseña) y de todas las actividades que ocurran bajo tu Cuenta, sea que las hayas realizado tú u otra persona autorizada por ti.\n\nDebes notificarnos de inmediato ante cualquier sospecha de uso no autorizado de tu Cuenta o de una violación de seguridad. PRODEX no es responsable de pérdidas derivadas del uso no autorizado de tu Cuenta cuando dicho uso resulte de una falla en el resguardo de tus propias credenciales.\n\nEl titular de la Cuenta (la empresa que la contrató) es responsable de gestionar los usuarios internos que autorice dentro de su Espacio de Trabajo, incluyendo la asignación de roles y permisos, la revocación oportuna de accesos cuando un colaborador deje de estar autorizado, y el cumplimiento de estos Términos por parte de dichos usuarios internos.",
                'en' => "You must provide truthful, complete, and current information when creating your Account, and keep it up to date while you use it. You are responsible for maintaining the confidentiality of your access credentials (username and password) and for all activity that occurs under your Account, whether carried out by you or by another person you authorized.\n\nYou must notify us immediately of any suspected unauthorized use of your Account or any security breach. PRODEX is not responsible for losses arising from unauthorized use of your Account where that use results from a failure to safeguard your own credentials.\n\nThe Account holder (the business that contracted it) is responsible for managing the internal users it authorizes within its Workspace, including assigning roles and permissions, promptly revoking access when a team member is no longer authorized, and ensuring those internal users comply with these Terms.",
            ],
            'payments' => [
                'es' => "Las Suscripciones de pago se facturan por adelantado, de forma mensual o anual según el ciclo que elijas, y se renuevan automáticamente al final de cada Período de Facturación salvo que la canceles conforme a la sección 12. Al proporcionar un método de pago, autorizas a PRODEX (o al proveedor de pago correspondiente, incluyendo Paddle cuando actúa como comerciante registrado) a cargar dicho método de forma recurrente por el importe del Plan vigente, más los impuestos aplicables.\n\nCuando Paddle actúa como comerciante registrado (Merchant of Record) para tu Suscripción, Paddle es quien te vende la Suscripción, procesa el cargo, determina y aplica los impuestos correspondientes a tu ubicación, y emite el comprobante fiscal de esa transacción a tu nombre; PRODEX recibe de Paddle la liquidación correspondiente por el servicio prestado. Para otras Suscripciones, el pago puede procesarse mediante otro proveedor de pago habilitado en el Sitio, en cuyo caso dicho proveedor procesa el cargo directamente conforme a sus propias condiciones.\n\nLos detalles sobre fallos de pago, suspensión, cancelación, reanudación y reembolsos se describen en las secciones 11 a 14 de estos Términos y, de forma más específica, en la Política de Reembolsos y Cancelaciones.",
                'en' => "Paid Subscriptions are billed in advance, monthly or annually depending on the cycle you choose, and automatically renew at the end of each Billing Period unless you cancel under Section 12. By providing a payment method, you authorize PRODEX (or the applicable payment provider, including Paddle when it acts as Merchant of Record) to recurringly charge that method for the amount of the then-current Plan, plus applicable taxes.\n\nWhen Paddle acts as Merchant of Record for your Subscription, Paddle is the party that sells you the Subscription, processes the charge, determines and applies the taxes applicable to your location, and issues the tax invoice for that transaction in your name; PRODEX receives from Paddle the corresponding settlement for the service provided. For other Subscriptions, payment may be processed through another payment provider enabled on the Site, in which case that provider processes the charge directly under its own terms.\n\nDetails on failed payments, suspension, cancellation, resumption, and refunds are set out in Sections 11 through 14 of these Terms and, in more detail, in the Refund & Cancellation Policy.",
            ],
            'prohibited' => [
                'es' => "Al utilizar el Servicio, aceptas no incurrir, ni permitir que un tercero incurra a través de tu Cuenta, en ninguna de las siguientes conductas:\n\na) Usar el Servicio para actividades ilegales, fraudulentas, o para almacenar, procesar o distribuir contenido ilícito.\n\nb) Intentar acceder sin autorización a Espacios de Trabajo, cuentas o datos de otros Clientes, o a cualquier sistema, red o credencial de PRODEX.\n\nc) Introducir o intentar introducir virus, malware, ransomware u otro código malicioso en el Servicio.\n\nd) Realizar ataques de denegación de servicio, escaneo de vulnerabilidades no autorizado, o cualquier intento de comprometer la seguridad o disponibilidad del Servicio.\n\ne) Utilizar procesos automatizados (bots, scraping, extracción masiva de datos) para acceder al Servicio de forma que exceda un uso razonable, sobrecargue la infraestructura, o eluda controles técnicos o límites de uso del Plan contratado.\n\nf) Intentar eludir, deshabilitar o interferir con las funciones de seguridad, autenticación, facturación o control de acceso del Servicio.\n\ng) Revender, sublicenciar o poner a disposición de terceros no autorizados el acceso al Servicio fuera de lo expresamente permitido en la sección 5.\n\nh) Suplantar la identidad de otra persona o entidad, o falsear tu afiliación con alguna persona o entidad.\n\ni) Utilizar el Servicio de cualquier forma que infrinja derechos de propiedad intelectual, privacidad u otros derechos de terceros.\n\nEl incumplimiento de esta sección puede resultar en la suspensión o terminación inmediata de tu Cuenta conforme a la sección 26, sin perjuicio de cualquier otra acción legal que corresponda a PRODEX.",
                'en' => "By using the Service, you agree not to engage in, and not to allow any third party to engage in through your Account, any of the following:\n\na) Using the Service for illegal or fraudulent activity, or to store, process, or distribute unlawful content.\n\nb) Attempting unauthorized access to other Customers' Workspaces, accounts, or data, or to any PRODEX system, network, or credential.\n\nc) Introducing or attempting to introduce viruses, malware, ransomware, or other malicious code into the Service.\n\nd) Carrying out denial-of-service attacks, unauthorized vulnerability scanning, or any attempt to compromise the security or availability of the Service.\n\ne) Using automated processes (bots, scraping, mass data extraction) to access the Service in a way that exceeds reasonable use, overloads infrastructure, or circumvents technical controls or the usage limits of the contracted Plan.\n\nf) Attempting to circumvent, disable, or interfere with the Service's security, authentication, billing, or access-control features.\n\ng) Reselling, sublicensing, or making the Service available to unauthorized third parties beyond what is expressly permitted in Section 5.\n\nh) Impersonating another person or entity, or misrepresenting your affiliation with any person or entity.\n\ni) Using the Service in any way that infringes the intellectual property, privacy, or other rights of third parties.\n\nBreach of this section may result in immediate suspension or termination of your Account under Section 26, without prejudice to any other legal action available to PRODEX.",
            ],
            'intellectual_property' => [
                'es' => "El Servicio, incluyendo su software, código fuente, interfaces, diseño visual, documentación, la marca PRODEX y sus logotipos asociados, son propiedad de PRODEX o de sus licenciantes y están protegidos por leyes de propiedad intelectual. Ninguna disposición de estos Términos te otorga derecho alguno sobre dichos elementos, salvo la licencia limitada de uso descrita en la sección 5.\n\nNo puedes usar el nombre \"PRODEX\", sus logotipos ni ninguna marca asociada sin nuestro consentimiento previo y por escrito, salvo lo estrictamente necesario para hacer referencia veraz al Servicio (por ejemplo, mencionar que tu empresa lo utiliza).\n\nSi nos proporcionas sugerencias, ideas o comentarios sobre el Servicio (\"Retroalimentación\"), nos otorgas una licencia perpetua, irrevocable, mundial y libre de regalías para utilizar dicha Retroalimentación con el fin de operar, mantener y mejorar el Servicio, sin obligación de compensarte ni de atribuirte su autoría.",
                'en' => "The Service, including its software, source code, interfaces, visual design, documentation, the PRODEX brand, and its associated logos, are owned by PRODEX or its licensors and are protected by intellectual-property law. Nothing in these Terms grants you any right in those items, other than the limited license to use them described in Section 5.\n\nYou may not use the \"PRODEX\" name, its logos, or any associated mark without our prior written consent, except as strictly necessary to accurately refer to the Service (for example, mentioning that your business uses it).\n\nIf you provide us suggestions, ideas, or comments about the Service (\"Feedback\"), you grant us a perpetual, irrevocable, worldwide, royalty-free license to use that Feedback to operate, maintain, and improve the Service, with no obligation to compensate you or attribute it to you.",
            ],
            'liability' => [
                'es' => "En la medida máxima permitida por la ley aplicable, en ningún caso PRODEX, sus directores, empleados o proveedores serán responsables frente a ti por daños indirectos, incidentales, especiales, consecuentes, punitivos, o por lucro cesante, pérdida de ingresos, pérdida de datos, pérdida de reputación comercial u otras pérdidas intangibles, derivados del uso o la imposibilidad de usar el Servicio, incluso si se nos advirtió de la posibilidad de dichos daños.\n\nEn la medida máxima permitida por la ley aplicable, la responsabilidad total y agregada de PRODEX frente a ti por cualquier reclamo derivado de o relacionado con estos Términos o el Servicio, ya sea contractual, extracontractual o de cualquier otra naturaleza, no excederá el monto total efectivamente pagado por ti a PRODEX por el Servicio durante los doce (12) meses inmediatamente anteriores al hecho que dio origen al reclamo.\n\nEsta limitación no aplica a: (a) tu obligación de pago por el Servicio efectivamente utilizado; (b) tu obligación de indemnización bajo la sección 24; (c) daños que resulten de dolo o negligencia grave comprobada de PRODEX; ni (d) cualquier responsabilidad que, conforme a la ley aplicable, no pueda ser excluida o limitada contractualmente (por ejemplo, ciertos derechos irrenunciables de consumidores). En dichos casos, la responsabilidad de PRODEX se limita al mínimo que la ley aplicable permita.",
                'en' => "To the maximum extent permitted by applicable law, in no event will PRODEX, its directors, employees, or suppliers be liable to you for indirect, incidental, special, consequential, or punitive damages, or for lost profits, lost revenue, lost data, loss of business reputation, or other intangible losses, arising from the use or inability to use the Service, even if advised of the possibility of such damages.\n\nTo the maximum extent permitted by applicable law, PRODEX's total aggregate liability to you for any claim arising out of or related to these Terms or the Service, whether in contract, tort, or otherwise, will not exceed the total amount actually paid by you to PRODEX for the Service during the twelve (12) months immediately preceding the event giving rise to the claim.\n\nThis limitation does not apply to: (a) your payment obligation for the Service actually used; (b) your indemnification obligation under Section 24; (c) damages resulting from PRODEX's proven willful misconduct or gross negligence; or (d) any liability that, under applicable law, cannot be contractually excluded or limited (for example, certain non-waivable consumer rights). In those cases, PRODEX's liability is limited to the minimum extent applicable law allows.",
            ],
            'governing_law' => [
                'es' => "Estos Términos se rigen e interpretan de conformidad con las leyes de la República de Honduras, sin dar efecto a sus disposiciones sobre conflicto de leyes, sin perjuicio de los derechos imperativos que correspondan al usuario conforme a la legislación de su propia jurisdicción cuando dicha legislación resulte aplicable de forma obligatoria.\n\nCualquier controversia derivada de o relacionada con estos Términos que no pueda resolverse mediante negociación directa entre las partes se someterá a los tribunales competentes de Honduras, salvo que una norma imperativa aplicable a un usuario que califique como consumidor en su jurisdicción disponga un fuero distinto que no pueda excluirse contractualmente, en cuyo caso prevalecerá dicha norma imperativa.\n\nAntes de iniciar un procedimiento formal, ambas partes procurarán de buena fe resolver cualquier controversia mediante negociación directa, contactando a PRODEX a través de los canales de la sección 30.",
                'en' => "These Terms are governed by and construed in accordance with the laws of the Republic of Honduras, without giving effect to its conflict-of-laws provisions, without prejudice to any non-waivable rights available to the user under the law of their own jurisdiction where that law applies on a mandatory basis.\n\nAny dispute arising out of or related to these Terms that cannot be resolved through direct negotiation between the parties will be submitted to the competent courts of Honduras, unless a mandatory rule applicable to a user who qualifies as a consumer in their jurisdiction provides for a different venue that cannot be contractually excluded, in which case that mandatory rule prevails.\n\nBefore initiating a formal proceeding, both parties will make a good-faith effort to resolve any dispute through direct negotiation, by contacting PRODEX through the channels in Section 30.",
            ],
        ];
    }

    private function privacyContent(): array
    {
        return [
            'introduction' => [
                'es' => "Esta Política de Privacidad explica cómo PRODEX recopila, utiliza, comparte y protege la información al operar el Sitio (prodexhub.cloud) y el Servicio. Se aplica tanto a los visitantes del Sitio como a las empresas y usuarios que contratan y utilizan el Servicio.\n\nEsta política debe leerse junto con los Términos y Condiciones y la Política de Reembolsos y Cancelaciones. Al usar el Sitio o el Servicio, reconoces haber leído esta Política de Privacidad.\n\nPRODEX es una plataforma de gestión empresarial multi-tenant: cada empresa cliente administra su propio Espacio de Trabajo. La sección 2 explica una distinción importante sobre cómo se aplica esta política a los distintos tipos de datos que existen dentro del Servicio.",
                'en' => "This Privacy Policy explains how PRODEX collects, uses, shares, and protects information when operating the Site (prodexhub.cloud) and the Service. It applies both to Site visitors and to the businesses and users that contract and use the Service.\n\nThis policy should be read together with the Terms of Service and the Refund & Cancellation Policy. By using the Site or the Service, you acknowledge you have read this Privacy Policy.\n\nPRODEX is a multi-tenant business-management platform: each business customer manages its own Workspace. Section 2 explains an important distinction in how this policy applies to the different categories of data that exist within the Service.",
            ],
            'data_collection' => [
                'es' => "Recopilamos directamente la información que nos proporcionas al: (a) registrar una Cuenta (nombre, correo electrónico, nombre de la empresa, subdominio elegido, y opcionalmente número de teléfono para recordatorios por SMS); (b) contratar o gestionar una Suscripción (información de facturación necesaria para emitir comprobantes, tal como nombre o razón social, correo de facturación y, cuando aplique, datos fiscales; ver también la sección 8 sobre pagos); (c) contactar a nuestro equipo de soporte o ventas (el contenido de tu consulta y los datos de contacto que nos proporciones); y (d) completar formularios disponibles en el Sitio.\n\nNo recopilamos directamente, ni almacenamos en nuestros propios servidores, los datos completos de tu tarjeta de pago; dicha información es capturada y procesada directamente por nuestro proveedor de pagos conforme a la sección 8.",
                'en' => "We collect directly the information you provide when you: (a) register an Account (name, email address, company name, chosen subdomain, and optionally a phone number for SMS reminders); (b) contract or manage a Subscription (billing information necessary to issue invoices, such as name or company name, billing email, and, where applicable, tax details; see also Section 8 on payments); (c) contact our support or sales team (the content of your inquiry and the contact details you provide); and (d) complete forms available on the Site.\n\nWe do not directly collect, nor store on our own servers, your full payment card details; that information is captured and processed directly by our payment provider under Section 8.",
            ],
            'data_usage' => [
                'es' => "Utilizamos la información descrita en la sección 3 (y la información técnica descrita en la sección 4) para las siguientes finalidades: (a) prestar, operar y mantener el Servicio, incluyendo la autenticación de tu Cuenta; (b) procesar pagos y gestionar la facturación de tu Suscripción; (c) prevenir fraude, abuso y actividades no autorizadas, y mantener la seguridad del Servicio; (d) brindarte soporte técnico y responder tus consultas; (e) enviarte comunicaciones operativas relacionadas con tu Cuenta (confirmaciones, avisos de pago, cambios en el Servicio o en estas políticas); (f) cuando hayas dado tu consentimiento, enviarte comunicaciones de marketing sobre el Servicio, que puedes cancelar en cualquier momento; (g) realizar analítica agregada sobre el uso del Sitio y del Servicio para entender y mejorar su funcionamiento; y (h) cumplir obligaciones legales, contables y fiscales aplicables a PRODEX como prestador del Servicio.\n\nNo vendemos tus datos personales a terceros para que estos los utilicen con fines propios de marketing.",
                'en' => "We use the information described in Section 3 (and the technical information described in Section 4) for the following purposes: (a) providing, operating, and maintaining the Service, including authenticating your Account; (b) processing payments and managing your Subscription's billing; (c) preventing fraud, abuse, and unauthorized activity, and maintaining the security of the Service; (d) providing technical support and responding to your inquiries; (e) sending you operational communications related to your Account (confirmations, payment notices, changes to the Service or these policies); (f) where you have given consent, sending you marketing communications about the Service, which you may opt out of at any time; (g) performing aggregated analytics on Site and Service usage to understand and improve its operation; and (h) complying with legal, accounting, and tax obligations applicable to PRODEX as the Service provider.\n\nWe do not sell your personal data to third parties for their own marketing purposes.",
            ],
            'cookies_usage' => [
                'es' => "Utilizamos cookies estrictamente necesarias para el funcionamiento del Sitio y del Servicio (por ejemplo, mantener tu sesión iniciada y recordar tu idioma preferido), las cuales no requieren consentimiento previo conforme a las prácticas habituales de la industria, ya que sin ellas el Servicio no podría prestarse correctamente.\n\nCuando estén habilitadas, también podemos utilizar cookies analíticas (para entender el uso agregado del Sitio) y, en su caso, cookies de marketing, únicamente con tu consentimiento previo otorgado mediante el panel de preferencias de cookies disponible en el Sitio. Puedes cambiar tus preferencias de cookies en cualquier momento a través de dicho panel o mediante la configuración de tu navegador; deshabilitar cookies no esenciales no afecta tu capacidad de usar las funciones principales del Servicio, pero deshabilitar cookies esenciales puede impedir el inicio de sesión y otras funciones básicas.",
                'en' => "We use cookies that are strictly necessary for the Site and Service to function (for example, keeping you signed in and remembering your preferred language), which do not require prior consent under standard industry practice, since the Service could not be properly provided without them.\n\nWhen enabled, we may also use analytics cookies (to understand aggregate Site usage) and, where applicable, marketing cookies, only with your prior consent given through the cookie-preferences panel available on the Site. You can change your cookie preferences at any time through that panel or through your browser settings; disabling non-essential cookies does not affect your ability to use the Service's core functions, but disabling essential cookies may prevent sign-in and other basic functions.",
            ],
            'third_party' => [
                'es' => "Compartimos datos personales únicamente con las categorías de terceros descritas en la sección 9 (proveedores y subencargados) y en la medida necesaria para las finalidades descritas en la sección 6, incluyendo proveedores de infraestructura en la nube, proveedores de correo electrónico transaccional, y nuestro proveedor de pagos (incluyendo Paddle cuando actúa como comerciante registrado). También podemos divulgar información cuando sea razonablemente necesario para: cumplir una obligación legal o un requerimiento válido de una autoridad competente; hacer valer estos Términos o proteger los derechos, la propiedad o la seguridad de PRODEX, nuestros Clientes o el público; o en el contexto de una fusión, adquisición o venta de activos, sujeto a las mismas protecciones descritas en esta política.\n\nNo compartimos datos personales con terceros para que los utilicen con fines de marketing propio ajenos a la prestación del Servicio.",
                'en' => "We share personal data only with the categories of third parties described in Section 9 (providers and sub-processors) and to the extent necessary for the purposes described in Section 6, including cloud infrastructure providers, transactional email providers, and our payment provider (including Paddle when it acts as Merchant of Record). We may also disclose information when reasonably necessary to: comply with a legal obligation or a valid request from a competent authority; enforce these Terms or protect the rights, property, or safety of PRODEX, our Customers, or the public; or in connection with a merger, acquisition, or asset sale, subject to the same protections described in this policy.\n\nWe do not share personal data with third parties for their own marketing purposes unrelated to providing the Service.",
            ],
            'data_protection' => [
                'es' => "Implementamos medidas técnicas y organizativas razonables para proteger la información que procesamos, incluyendo: cifrado de datos en tránsito mediante HTTPS/TLS; aislamiento de datos por Espacio de Trabajo dentro de nuestra arquitectura multi-tenant; controles de acceso basados en roles; y prácticas de respaldo periódico. Nuestro personal solo accede a los Datos del Cliente en la medida necesaria para brindar soporte técnico, resolver incidentes o cumplir una obligación legal.\n\nNinguna medida de seguridad es infalible. En caso de un incidente de seguridad que comprometa datos personales de forma que la ley aplicable exija notificación, notificaremos a los afectados y, cuando corresponda, a la autoridad competente, conforme a los plazos y medios que dicha ley establezca.",
                'en' => "We implement reasonable technical and organizational measures to protect the information we process, including: encryption of data in transit via HTTPS/TLS; data isolation per Workspace within our multi-tenant architecture; role-based access controls; and periodic backup practices. Our staff access Customer Data only to the extent necessary to provide technical support, resolve incidents, or comply with a legal obligation.\n\nNo security measure is infallible. In the event of a security incident that compromises personal data in a way that applicable law requires notification, we will notify affected individuals and, where applicable, the competent authority, within the timeframes and through the means that law establishes.",
            ],
            'user_rights' => [
                'es' => "Respecto de los datos descritos en la sección 2(A) (los que PRODEX trata para gestionar su propia relación contigo), y en la medida que la legislación aplicable te reconozca estos derechos, puedes: acceder a tus datos personales; solicitar su rectificación o actualización cuando sean inexactos; solicitar su eliminación, sujeto a las obligaciones legales de conservación descritas en la sección 12; oponerte a determinados tratamientos basados en interés legítimo; retirar tu consentimiento en cualquier momento cuando el tratamiento se base en él, sin afectar la licitud del tratamiento previo; y, cuando la ley aplicable lo reconozca, solicitar la portabilidad de tus datos en un formato estructurado de uso común.\n\nPara ejercer estos derechos, contáctanos a través de los canales indicados en la sección 18. Podemos solicitarte información adicional para verificar tu identidad antes de procesar la solicitud, y podemos denegar o limitar una solicitud cuando la ley aplicable lo permita (por ejemplo, cuando exista una obligación legal de conservar la información).\n\nSi los datos sobre los que ejerces un derecho corresponden en realidad a información que una empresa cliente introdujo sobre ti dentro de su propio Espacio de Trabajo (sección 2(B)), debes dirigir tu solicitud directamente a esa empresa, ya que es ella quien controla y decide sobre dicha información; PRODEX colaborará con esa empresa en la medida técnica necesaria cuando así se nos solicite.",
                'en' => "With respect to the data described in Section 2(A) (the data PRODEX processes to manage its own relationship with you), and to the extent applicable law grants you these rights, you may: access your personal data; request correction or updating when it is inaccurate; request deletion, subject to the legal retention obligations described in Section 12; object to certain processing based on legitimate interest; withdraw your consent at any time where processing is based on it, without affecting the lawfulness of processing carried out beforehand; and, where applicable law recognizes it, request portability of your data in a structured, commonly used format.\n\nTo exercise these rights, contact us through the channels listed in Section 18. We may ask you for additional information to verify your identity before processing the request, and we may deny or limit a request where applicable law permits (for example, where there is a legal obligation to retain the information).\n\nIf the data over which you are exercising a right is actually information a business customer entered about you within its own Workspace (Section 2(B)), you should direct your request to that business directly, since it controls and decides on that information; PRODEX will cooperate with that business to the extent technically necessary when asked to do so.",
            ],
            'contact_info' => [
                'es' => "Si tienes preguntas sobre esta Política de Privacidad o deseas ejercer alguno de los derechos descritos en la sección 13, contáctanos a través de los canales de contacto publicados en el pie de página de este sitio.",
                'en' => "If you have questions about this Privacy Policy or wish to exercise any of the rights described in Section 13, contact us through the contact channels published in this site's footer.",
            ],
        ];
    }

    private function refundContent(): array
    {
        return [
            'overview' => [
                'es' => "Esta Política de Reembolsos y Cancelaciones (esta \"Política\") explica cuándo un cargo realizado por PRODEX es reembolsable, cómo funciona la cancelación de una Suscripción, y qué proceso seguir para solicitar un reembolso. Esta Política forma parte integral de los Términos y Condiciones de PRODEX y prevalece sobre ellos en caso de conflicto respecto específicamente de reembolsos y cancelaciones.\n\nEsta Política aplica a las Suscripciones contratadas a través del Sitio, ya sea que el pago se procese directamente por PRODEX, por Paddle.com Market Limited (\"Paddle\") en su calidad de comerciante registrado (Merchant of Record), o por otro proveedor de pago habilitado en el Sitio. La sección 8 explica las particularidades cuando Paddle es quien procesa el reembolso.\n\nNinguna disposición de esta Política limita ningún derecho de reembolso, cancelación o desistimiento que la legislación de protección al consumidor aplicable a ti reconozca de forma irrenunciable; en caso de conflicto entre esta Política y dicha legislación, prevalece la legislación aplicable en la medida en que sea de carácter imperativo.",
                'en' => "This Refund & Cancellation Policy (this \"Policy\") explains when a charge made by PRODEX is refundable, how cancelling a Subscription works, and what process to follow to request a refund. This Policy is an integral part of the PRODEX Terms of Service and prevails over them in the event of a conflict specifically regarding refunds and cancellations.\n\nThis Policy applies to Subscriptions contracted through the Site, whether payment is processed directly by PRODEX, by Paddle.com Market Limited (\"Paddle\") in its capacity as Merchant of Record, or by another payment provider enabled on the Site. Section 8 explains the specifics of when Paddle handles the refund.\n\nNothing in this Policy limits any refund, cancellation, or withdrawal right that consumer-protection law applicable to you grants on a non-waivable basis; in the event of a conflict between this Policy and that law, the applicable law prevails to the extent it is mandatory.",
            ],
            'subscriptions_trials' => [
                'es' => "Determinados Planes, incluyendo el Plan Emprendedor en su configuración actual, incluyen un período de prueba gratuita de hasta 30 días antes de que se realice el primer cargo. Durante la prueba puedes cancelar en cualquier momento sin costo alguno desde tu Cuenta.\n\nSi no cancelas antes de que finalice el período de prueba, tu Suscripción se activa automáticamente al terminar la prueba y se realiza el primer cargo correspondiente al Plan y ciclo de facturación (mensual o anual) que hayas seleccionado. A partir de ese momento, la Suscripción se renueva automáticamente al final de cada Período de Facturación por el mismo importe (salvo un cambio de precio notificado conforme a los Términos), hasta que la canceles conforme a la sección 3 de esta Política.\n\nTe recomendamos revisar la fecha en que finaliza tu período de prueba, disponible en tu panel de Cuenta, si no deseas continuar con la Suscripción de pago.",
                'en' => "Certain Plans, including the Emprendedor (Starter) Plan under its current configuration, include a free trial period of up to 30 days before the first charge occurs. During the trial you may cancel at any time at no cost from your Account.\n\nIf you do not cancel before the trial period ends, your Subscription automatically activates when the trial ends and the first charge is made for the Plan and billing cycle (monthly or annual) you selected. From that point on, the Subscription automatically renews at the end of each Billing Period for the same amount (subject to any price change notified under the Terms), until you cancel it under Section 3 of this Policy.\n\nWe recommend checking the date your trial period ends, available in your Account dashboard, if you do not wish to continue with the paid Subscription.",
            ],
            'cancellations' => [
                'es' => "Puedes cancelar la renovación automática de tu Suscripción en cualquier momento, sin necesidad de justificar el motivo, desde el panel de tu Cuenta o solicitándolo a soporte conforme a la sección 7.\n\nUna cancelación es una cancelación de la renovación futura, no una terminación inmediata del acceso: conservas acceso completo al Servicio hasta la fecha de finalización del Período de Facturación que ya pagaste (la \"fecha efectiva de cancelación\"). A partir de esa fecha, no se generará ningún cargo adicional, la renovación automática queda desactivada y el acceso al Servicio se suspende.\n\nSi cambias de opinión antes de la fecha efectiva de cancelación, puedes reanudar la renovación automática conforme a la sección 13 de los Términos y Condiciones, sujeto a que ello sea técnicamente posible conforme a las reglas del proveedor de pago utilizado al momento de la solicitud.\n\nCancelar la renovación automática no genera, por sí solo, un reembolso del Período de Facturación ya pagado; dicho período ya fue prestado o está en curso de prestación hasta su fecha de finalización, conforme se explica en la sección 5.",
                'en' => "You may cancel auto-renewal of your Subscription at any time, without needing to provide a reason, from your Account dashboard or by requesting it from support under Section 7.\n\nA cancellation stops future renewal — it is not an immediate termination of access: you retain full access to the Service through the end date of the Billing Period you already paid for (the \"effective cancellation date\"). From that date onward, no further charge will be generated, auto-renewal is turned off, and access to the Service is suspended.\n\nIf you change your mind before the effective cancellation date, you may resume auto-renewal under Section 13 of the Terms of Service, provided that is technically possible under the rules of the payment provider used at the time of the request.\n\nCancelling auto-renewal does not, by itself, generate a refund of the Billing Period already paid for; that period has already been, or is in the course of being, provided through its end date, as explained in Section 5.",
            ],
            'billing_errors' => [
                'es' => "Si detectas un error de facturación, tienes derecho a que lo investiguemos y, cuando corresponda, lo corrijamos mediante un reembolso total o parcial. Constituyen errores de facturación, entre otros:\n\na) Cobro duplicado: se te cobró más de una vez por el mismo Período de Facturación del mismo Plan.\n\nb) Importe incorrecto: se te cobró un monto distinto al precio vigente de tu Plan al momento del cargo (por ejemplo, por un error técnico o de configuración).\n\nc) Transacción no reconocida: identificas un cargo asociado a tu método de pago que no corresponde a ninguna Suscripción o acción autorizada por ti en PRODEX.\n\nd) Cargo posterior a una cancelación efectiva: se te cobró un Período de Facturación posterior a la fecha efectiva de cancelación de tu Suscripción, pese a haber cancelado correctamente antes de dicha fecha.\n\nAnte cualquiera de estos casos, contáctanos conforme a la sección 7 con la información de la transacción; investigaremos el caso y, de confirmarse el error, procesaremos el reembolso correspondiente al importe efectivamente erróneo.",
                'en' => "If you identify a billing error, you have the right to have it investigated and, where confirmed, corrected through a full or partial refund. Billing errors include, among others:\n\na) Duplicate charge: you were charged more than once for the same Billing Period of the same Plan.\n\nb) Incorrect amount: you were charged an amount different from your Plan's price in effect at the time of the charge (for example, due to a technical or configuration error).\n\nc) Unrecognized transaction: you identify a charge against your payment method that does not correspond to any Subscription or action you authorized in PRODEX.\n\nd) Charge after an effective cancellation: you were charged for a Billing Period after your Subscription's effective cancellation date, despite having correctly cancelled before that date.\n\nFor any of these cases, contact us under Section 7 with the transaction information; we will investigate the matter and, if the error is confirmed, process a refund for the amount actually charged in error.",
            ],
            'refund_eligibility' => [
                'es' => "Fuera de los errores de facturación descritos en la sección 4, y salvo que la ley aplicable te otorgue un derecho de desistimiento o reembolso distinto que no pueda excluirse contractualmente, los cargos por Períodos de Facturación ya transcurridos o en curso corresponden a Servicio efectivamente puesto a tu disposición y, por regla general, no son reembolsables por el solo hecho de decidir no continuar utilizando el Servicio o de haberlo usado poco.\n\nSin perjuicio de lo anterior, evaluamos de buena fe, caso por caso, solicitudes de reembolso voluntario fuera de los supuestos anteriores, incluyendo situaciones de indisponibilidad grave y prolongada del Servicio directamente atribuible a una falla de PRODEX (y no a mantenimiento programado, causas de fuerza mayor, o fallas de terceros ajenos a PRODEX) que te haya impedido de forma sustancial utilizar el Servicio durante el período por el que reclamas el reembolso. En dichos casos, PRODEX puede, a su discreción razonable, otorgar un reembolso total o parcial, o un crédito equivalente aplicable a un Período de Facturación futuro.\n\nSi realizaste tu pago a través de Paddle como comerciante registrado, cualquier reembolso aprobado conforme a esta sección será procesado por Paddle, conforme se explica en la sección 8, incluyendo el tiempo de procesamiento y el método de devolución (que será, por regla general, el mismo método de pago original), la conversión de moneda que hubiera aplicado a la transacción original, y sin cargo adicional por parte de PRODEX por dicho reembolso (Paddle puede aplicar sus propias reglas de procesamiento).",
                'en' => "Outside the billing errors described in Section 4, and unless applicable law grants you a different withdrawal or refund right that cannot be contractually excluded, charges for Billing Periods that have already elapsed or are in progress correspond to Service actually made available to you and, as a general rule, are not refundable simply because you decide not to continue using the Service or because you used it little.\n\nNotwithstanding the above, we evaluate in good faith, on a case-by-case basis, voluntary refund requests outside the scenarios above, including situations of severe and prolonged Service unavailability directly attributable to a PRODEX failure (and not to scheduled maintenance, force-majeure causes, or failures of third parties outside PRODEX's control) that substantially prevented you from using the Service during the period for which you are claiming a refund. In those cases, PRODEX may, in its reasonable discretion, grant a full or partial refund, or an equivalent credit applicable to a future Billing Period.\n\nIf you paid through Paddle as Merchant of Record, any refund approved under this section will be processed by Paddle, as explained in Section 8, including the processing time and refund method (generally the same original payment method), any currency conversion that applied to the original transaction, and with no additional fee charged by PRODEX for that refund (Paddle may apply its own processing rules).",
            ],
            'chargebacks' => [
                'es' => "Si tienes una inquietud sobre un cargo, te pedimos que primero nos contactes conforme a la sección 7 para intentar resolverla directamente, en lugar de iniciar un contracargo (\"chargeback\") con tu banco o emisor de tarjeta sin darnos la oportunidad de investigar el caso. La mayoría de los errores de facturación se resuelven de forma más rápida a través de nuestro proceso directo de reembolso que a través de un contracargo.\n\nSi de buena fe presentas un contracargo por un cargo que consideras injustificado, colaboraremos con el proceso conforme a las reglas del proveedor de pago correspondiente (incluyendo Paddle cuando aplique). Sin embargo, el uso de contracargos como mecanismo para obtener un reembolso evitando nuestro proceso directo, cuando el cargo en cuestión corresponde efectivamente a Servicio prestado conforme a estos Términos y no existe un error de facturación real, puede constituir abuso del sistema de contracargos y una violación de la sección 15 de los Términos y Condiciones, y puede resultar en la suspensión o terminación de tu Cuenta.\n\nSi ya recibiste un reembolso voluntario de PRODEX o de Paddle por un cargo determinado, no debes además iniciar un contracargo por ese mismo cargo; hacerlo constituye un intento de doble recuperación del mismo importe y será tratado conforme al párrafo anterior.",
                'en' => "If you have a concern about a charge, we ask that you first contact us under Section 7 to try to resolve it directly, rather than initiating a chargeback with your bank or card issuer without giving us the chance to investigate. Most billing errors are resolved faster through our direct refund process than through a chargeback.\n\nIf you file a chargeback in good faith for a charge you believe is unjustified, we will cooperate with the process under the rules of the applicable payment provider (including Paddle where relevant). However, using chargebacks as a way to obtain a refund while bypassing our direct process, when the charge in question actually corresponds to Service provided under these Terms and there is no genuine billing error, may constitute abuse of the chargeback system and a violation of Section 15 of the Terms of Service, and may result in suspension or termination of your Account.\n\nIf you have already received a voluntary refund from PRODEX or Paddle for a given charge, you must not also initiate a chargeback for that same charge; doing so constitutes an attempt at double recovery of the same amount and will be treated under the preceding paragraph.",
            ],
            'how_to_request' => [
                'es' => "Para solicitar un reembolso o reportar un error de facturación, contáctanos a través de los canales de contacto publicados en el pie de página de este sitio, indicando:\n\na) El correo electrónico o identificador asociado a tu Cuenta.\n\nb) La fecha aproximada y, si la tienes, el número o referencia del cargo en cuestión.\n\nc) El importe cobrado y el motivo de tu solicitud (por ejemplo, cobro duplicado, importe incorrecto, transacción no reconocida, indisponibilidad del Servicio, u otro).\n\nd) Cualquier comprobante disponible (por ejemplo, captura del estado de cuenta o del comprobante de pago).\n\nProcuramos confirmar la recepción de tu solicitud dentro de los siguientes dos (2) días hábiles, e informarte el resultado de la revisión dentro de un plazo razonable, generalmente no mayor a diez (10) días hábiles, salvo que el caso requiera una investigación más extensa (por ejemplo, coordinación con Paddle u otro proveedor de pago). Si el reembolso es aprobado y procesado por Paddle, el tiempo efectivo en que el importe aparezca reflejado en tu método de pago depende adicionalmente de las políticas de procesamiento de Paddle y de tu entidad bancaria o emisora, y puede tomar varios días hábiles adicionales.",
                'en' => "To request a refund or report a billing error, contact us through the contact channels published in this site's footer, providing:\n\na) The email address or identifier associated with your Account.\n\nb) The approximate date and, if you have it, the number or reference of the charge in question.\n\nc) The amount charged and the reason for your request (for example, duplicate charge, incorrect amount, unrecognized transaction, Service unavailability, or other).\n\nd) Any supporting documentation available (for example, a screenshot of your statement or payment receipt).\n\nWe aim to acknowledge receipt of your request within two (2) business days, and to inform you of the outcome of our review within a reasonable time, generally no more than ten (10) business days, unless the case requires a more extensive investigation (for example, coordination with Paddle or another payment provider). If the refund is approved and processed by Paddle, the actual time it takes for the amount to appear back in your payment method additionally depends on Paddle's processing policies and your bank or card issuer, and may take several additional business days.",
            ],
            'payment_processor' => [
                'es' => "Para determinadas Suscripciones, Paddle.com Market Limited (\"Paddle\") actúa como comerciante registrado (Merchant of Record). Esto significa que, respecto de esas transacciones, Paddle —y no PRODEX— es la entidad que te vende la Suscripción, procesa tu pago, aplica los impuestos correspondientes, emite el comprobante fiscal, y procesa cualquier reembolso aprobado.\n\nCuando un reembolso corresponde a una transacción procesada por Paddle, PRODEX aprueba la solicitud conforme a esta Política, pero es Paddle quien ejecuta técnicamente la devolución del dinero, siguiendo sus propios procedimientos operativos, plazos de procesamiento y método de devolución (por regla general, el mismo método de pago original). Paddle mantiene entornos de procesamiento separados para pruebas (\"Sandbox\") y para producción (\"Live\"); un reembolso solo puede procesarse dentro del mismo entorno en el que se realizó el cargo original.\n\nSi tienes una consulta específica sobre el estado de un reembolso ya aprobado y en procesamiento por Paddle, puedes contactarnos y coordinaremos contigo el seguimiento correspondiente.",
                'en' => "For certain Subscriptions, Paddle.com Market Limited (\"Paddle\") acts as Merchant of Record. This means that, for those transactions, Paddle — not PRODEX — is the entity that sells you the Subscription, processes your payment, applies the applicable taxes, issues the tax invoice, and processes any approved refund.\n\nWhen a refund relates to a transaction processed by Paddle, PRODEX approves the request under this Policy, but Paddle is the one that technically executes the return of funds, following its own operating procedures, processing times, and refund method (generally the same original payment method). Paddle maintains separate processing environments for testing (\"Sandbox\") and production (\"Live\"); a refund can only be processed within the same environment in which the original charge was made.\n\nIf you have a specific question about the status of a refund already approved and being processed by Paddle, you can contact us and we will coordinate the appropriate follow-up with you.",
            ],
        ];
    }
};
