<template>
  <div class="portal-layout">
    <header class="pc-header"><div class="pc-header-inner"><router-link to="/dashboard" class="pc-brand"><span class="pc-brand-mark">P</span><span>Portal del cliente</span></router-link><nav class="pc-nav pc-nav-desktop"><router-link v-for="item in desktopNavItems" :key="item.to" :to="item.to" class="pc-nav-link">{{item.label}}</router-link></nav><div class="pc-header-actions"><div class="pc-user" @click.stop="menuOpen=!menuOpen"><div class="pc-avatar">{{initials}}</div><span>{{clientName}}</span><div v-if="menuOpen" class="pc-menu" @click.stop><div class="pc-menu-header"><strong>{{clientName}}</strong><small>Sesión iniciada</small></div><router-link to="/profile" class="pc-menu-item" @click.native="menuOpen=false">Perfil</router-link><button type="button" class="pc-menu-item pc-menu-danger" @click="logout">Cerrar sesión</button></div></div></div></div></header>
    <main class="pc-main"><router-view /></main>
    <nav class="pc-bottom-nav"><router-link v-for="item in navItems" :key="item.to" :to="item.to" class="pc-bottom-link"><span>{{item.label}}</span></router-link></nav>
  </div>
</template>
<script>
export default{data(){return{clientName:'',menuOpen:false,navItems:[{to:'/dashboard',label:'Inicio'},{to:'/invoices',label:'Facturas'},{to:'/quotations',label:'Cotizaciones'},{to:'/appointments',label:'Citas'},{to:'/contracts',label:'Contratos'},{to:'/payments',label:'Pagos'},{to:'/statement',label:'Estado de cuenta'},{to:'/help',label:'Ayuda'},{to:'/profile',label:'Perfil'}]}},computed:{initials(){return(this.clientName||'C').split(/\s+/).filter(Boolean).slice(0,2).map(w=>w[0].toUpperCase()).join('')||'C'},desktopNavItems(){return this.navItems.filter(i=>i.to!=='/profile')}},async mounted(){document.addEventListener('click',this.closeMenu);try{const{data}=await axios.get('/portal/me');this.clientName=data?.portal_client?.client?.name||'Cuenta'}catch(_){this.clientName='Cuenta'}},beforeDestroy(){document.removeEventListener('click',this.closeMenu)},methods:{closeMenu(){this.menuOpen=false},async logout(){await axios.post('/portal/logout');window.location.href='/portal/login'}}}
</script>
<style scoped>.portal-layout{min-height:100vh;display:flex;flex-direction:column;background:var(--pc-bg)}.pc-header{position:sticky;top:0;z-index:100;background:var(--pc-header-bg);border-bottom:1px solid var(--pc-border)}.pc-header-inner{max-width:1200px;margin:auto;padding:.75rem 1.25rem;display:flex;align-items:center;gap:1rem}.pc-brand{display:flex;align-items:center;gap:.6rem;text-decoration:none;color:var(--pc-text);font-weight:700}.pc-brand-mark,.pc-avatar{display:flex;align-items:center;justify-content:center;width:34px;height:34px;border-radius:10px;background:var(--pc-primary);color:white}.pc-nav{display:flex;gap:.25rem;flex:1}.pc-nav-link{padding:.5rem .65rem;text-decoration:none;color:var(--pc-text-muted);border-radius:8px}.pc-nav-link.router-link-active{color:var(--pc-primary);background:var(--pc-primary-50)}.pc-user{position:relative;display:flex;align-items:center;gap:.5rem;cursor:pointer}.pc-menu{position:absolute;right:0;top:calc(100% + .5rem);min-width:190px;background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:10px;box-shadow:var(--pc-shadow);padding:.4rem}.pc-menu-header{display:flex;flex-direction:column;padding:.6rem}.pc-menu-item{display:block;width:100%;box-sizing:border-box;padding:.55rem .65rem;border:0;background:none;text-align:left;text-decoration:none;color:var(--pc-text);cursor:pointer}.pc-menu-danger{color:var(--pc-danger)}.pc-main{width:100%;max-width:1200px;margin:0 auto;padding:1.5rem;box-sizing:border-box;flex:1}.pc-bottom-nav{display:none}@media(max-width:768px){.pc-nav-desktop{display:none}.pc-user>span{display:none}.pc-main{padding:1rem 1rem 5rem}.pc-bottom-nav{position:fixed;display:flex;bottom:0;left:0;right:0;background:var(--pc-surface);border-top:1px solid var(--pc-border);z-index:100;overflow-x:auto}.pc-bottom-link{flex:1;min-width:72px;text-align:center;padding:.75rem .35rem;text-decoration:none;color:var(--pc-text-muted);font-size:.72rem}.pc-bottom-link.router-link-active{color:var(--pc-primary)}}</style>