import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const { colors } = JSON.parse(fs.readFileSync(path.join(root, 'resources/brand/prodex.json'), 'utf8'));
const notice = '// Generated by scripts/generate-brand.mjs from resources/brand/prodex.json.\n';
const variables = Object.entries(colors).map(([name, value]) => `  --prodex-${name}: ${value};`).join('\n');
const rgb = value => value.slice(1).match(/../g).map(v => parseInt(v, 16)).join(', ');
const css = `/* Generated from resources/brand/prodex.json; do not edit. */
:root {
${variables}
  --prodex-ink-rgb: ${rgb(colors.ink)};
  --prodex-aqua-rgb: ${rgb(colors.aqua)};
  --primary-color: var(--prodex-ink);
  --primary-color-darker: var(--prodex-ink);
  --primary-color-soft: rgba(var(--prodex-aqua-rgb), .12);
  --primary-color-lighter: var(--prodex-ink);
  --primary-contrast: var(--prodex-white);
  --primary-text: var(--prodex-ink);
  --brand-accent: var(--prodex-aqua);
  --brand-focus: var(--prodex-ink);
}
`;
const scss = notice + Object.entries(colors).map(([name, value]) => `$prodex-${name}: ${value};`).join('\n') + '\n';
const outputs = {
  'public/css/prodex-brand.css': css,
  'resources/src/assets/styles/sass/prodex/_brand.generated.scss': scss,
};
for (const [file, content] of Object.entries(outputs)) {
  const target = path.join(root, file);
  if (process.argv.includes('--check')) {
    if (!fs.existsSync(target) || fs.readFileSync(target, 'utf8') !== content) throw new Error(`Stale brand output: ${file}`);
  } else fs.writeFileSync(target, content);
}

for (const file of fs.readdirSync(path.join(root, 'public')).filter(f => /^manifest.*\.webmanifest$/.test(f))) {
  const target = path.join(root, 'public', file);
  const manifest = JSON.parse(fs.readFileSync(target, 'utf8'));
  const before = JSON.stringify(manifest);
  manifest.theme_color = colors.ink;
  manifest.icons = [192, 512].map(size => ({ src: `/images/brand-assets/icons/icon-${size}.png`, sizes: `${size}x${size}`, type: 'image/png', purpose: 'any' }));
  const platformNames = {
    'manifest.webmanifest': ['PRODEX', 'PRODEX', 'Gestión empresarial con punto de venta'],
    'manifest-store.webmanifest': ['PRODEX Tienda', 'Tienda', 'Tienda en línea'],
    'manifest-portal.webmanifest': ['PRODEX Portal de clientes', 'Portal', 'Portal de clientes'],
    'manifest-customer-display.webmanifest': ['PRODEX Pantalla de cliente', 'Pantalla', 'Pantalla de cliente'],
  };
  if (platformNames[file]) {
    const [name, short_name, description] = platformNames[file];
    Object.assign(manifest, { name, short_name, description, lang: 'es-HN' });
  }
  if (process.argv.includes('--check')) {
    if (before !== JSON.stringify(manifest)) throw new Error(`Stale brand manifest: ${file}`);
  } else fs.writeFileSync(target, JSON.stringify(manifest, null, 2) + '\n');
}
