<template>
  <div class="portal-page portal-appointment-detail">
    <header class="pc-page-header"><div><h1 class="pc-page-title">{{ appointment.Ref || 'Cita' }}</h1><p class="pc-page-sub" v-if="appointment.scheduled_date">Programada para {{ appointment.scheduled_date }}</p></div><router-link to="/appointments" class="pc-link-back">&larr; Volver</router-link></header>
    <div v-if="loading" class="pc-inline-loading"><div class="pc-spinner"></div><span>Cargando...</span></div>
    <div v-else-if="error" class="pc-card pc-error"><div class="pc-error-icon">⚠️</div><h3 class="pc-error-title">{{ error.title }}</h3><p class="pc-error-text">{{ error.message }}</p><button type="button" class="pc-btn pc-btn-primary" @click="fetch">Intentar de nuevo</button></div>
    <div v-else-if="!appointment.id" class="pc-card pc-error"><div class="pc-error-icon">📭</div><h3 class="pc-error-title">Cita no encontrada</h3><p class="pc-error-text">No pudimos encontrar esta cita. Puede haber sido eliminada o pertenecer a otra cuenta.</p></div>
    <div v-else class="pc-card pc-detail">
      <div class="pc-detail-header"><span :class="'pc-badge pc-badge-' + badgeClass(appointment.status)">{{ statusLabel(appointment.status) }}</span><div class="pc-amount" v-if="appointment.total_amount">{{ formatMoney(appointment.total_amount) }}</div></div>
      <dl class="pc-meta-grid"><div><dt>Referencia</dt><dd>{{ appointment.Ref || '—' }}</dd></div><div><dt>Servicio</dt><dd>{{ appointment.service_item || '—' }}</dd></div><div><dt>Tipo</dt><dd>{{ appointment.job_type || '—' }}</dd></div><div><dt>Programada</dt><dd>{{ appointment.scheduled_date || '—' }}</dd></div><div><dt>Reservada</dt><dd>{{ appointment.created_at || '—' }}</dd></div><div><dt>Iniciada</dt><dd>{{ appointment.started_at || '—' }}</dd></div><div><dt>Completada</dt><dd>{{ appointment.completed_at || '—' }}</dd></div><div><dt>Técnico</dt><dd>{{ appointment.technician_name || '—' }}</dd></div><div><dt>Dispositivo</dt><dd>{{ deviceLabel || '—' }}</dd></div><div><dt>Cotización</dt><dd>{{ appointment.quote_amount ? formatMoney(appointment.quote_amount) : '—' }}</dd></div><div><dt>Pagado</dt><dd>{{ appointment.paid_amount != null ? formatMoney(appointment.paid_amount) : '—' }}</dd></div><div><dt>Estado del pago</dt><dd>{{ paymentStatusLabel(appointment.payment_status) }}</dd></div></dl>
      <div v-if="appointment.reported_issue" class="pc-block"><h3>Problema reportado</h3><p>{{ appointment.reported_issue }}</p></div><div v-if="appointment.diagnosis" class="pc-block"><h3>Diagnóstico</h3><p>{{ appointment.diagnosis }}</p></div><div v-if="appointment.notes" class="pc-block"><h3>Notas</h3><p>{{ appointment.notes }}</p></div>
    </div>
  </div>
</template>
<script>export default{data(){return{appointment:{},loading:true,error:null}},computed:{deviceLabel(){const a=this.appointment;return[a.device_brand,a.device_model,a.device_serial].filter(Boolean).join(' / ')}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;this.error=null;try{const{data}=await axios.get(`/portal/appointments/${this.$route.params.id}`);this.appointment=data||{}}catch(e){this.appointment={};const status=e?.response?.status;const msg=e?.response?.data?.message;if(status===404)this.error={title:'Cita no encontrada',message:msg||'No pudimos encontrar esta cita en tu cuenta.'};else if(status===403)this.error={title:'Acceso denegado',message:msg||'Tu sesión del portal no tiene permiso para ver esta cita.'};else if(status===401)this.error={title:'Sesión vencida',message:'Vuelve a iniciar sesión para consultar esta cita.'};else this.error={title:'No se pudo cargar la cita',message:msg||'Ocurrió un problema al cargar esta cita. Inténtalo de nuevo.'}}this.loading=false},formatMoney(n){if(n==null)return'0.00';return Number(n).toLocaleString('es-HN',{minimumFractionDigits:2,maximumFractionDigits:2})},badgeClass(s){const v=(s||'').toLowerCase();if(['completed','delivered','ready'].includes(v))return'paid';if(['pending','intake','diagnostic','quoted'].includes(v))return'pending';if(['in_progress','approved'].includes(v))return'progress';if(['cancelled','declined'].includes(v))return'partial';return'pending'},statusLabel(s){const v=(s||'').toLowerCase();return {completed:'Completada',delivered:'Entregada',ready:'Lista',pending:'Pendiente',intake:'Recepción',diagnostic:'Diagnóstico',quoted:'Cotizada',in_progress:'En progreso',approved:'Aprobada',cancelled:'Cancelada',declined:'Rechazada'}[v]||s||'Pendiente'},paymentStatusLabel(s){const v=(s||'').toLowerCase();return {paid:'Pagado',partial:'Parcial',unpaid:'Sin pagar',pending:'Pendiente'}[v]||s||'—'}}}</script>
<style scoped>.portal-appointment-detail{padding-bottom:1rem}.pc-page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap}.pc-page-title{font-size:1.5rem;font-weight:700;color:var(--pc-text);margin:0 0 .2rem}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:0}.pc-link-back{color:var(--pc-text-muted);text-decoration:none;font-size:.88rem}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius);box-shadow:var(--pc-shadow-sm);padding:1.5rem}.pc-detail-header{display:flex;justify-content:space-between;align-items:center;padding-bottom:1rem;border-bottom:1px solid var(--pc-border);margin-bottom:1.1rem}.pc-amount{font-size:1.4rem;font-weight:700}.pc-badge{display:inline-block;padding:.3rem .7rem;border-radius:999px;font-size:.78rem;font-weight:600}.pc-badge-paid{background:var(--pc-success-bg);color:var(--pc-success)}.pc-badge-pending{background:var(--pc-warning-bg);color:var(--pc-warning)}.pc-badge-progress{background:#dbeafe;color:#1d4ed8}.pc-badge-partial{background:#fee2e2;color:#b91c1c}.pc-meta-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:.85rem 1.5rem;margin:0 0 1.2rem}.pc-meta-grid div{display:flex;flex-direction:column}.pc-meta-grid dt{font-size:.72rem;text-transform:uppercase;color:var(--pc-text-soft);font-weight:600}.pc-meta-grid dd{margin:.15rem 0 0}.pc-block{margin-top:1rem}.pc-block h3{font-size:.95rem;margin:0 0 .4rem}.pc-block p{margin:0;padding:.85rem 1rem;background:var(--pc-surface-alt);border-radius:10px;white-space:pre-wrap}.pc-error{text-align:center;padding:2rem 1.5rem}.pc-error-icon{font-size:2.5rem}.pc-error-text{color:var(--pc-text-muted)}.pc-btn-primary{background:var(--pc-primary);color:#fff;border:0;border-radius:8px;padding:.6rem .9rem}.pc-inline-loading{display:flex;align-items:center;justify-content:center;gap:.75rem;padding:3rem}.pc-spinner{width:28px;height:28px;border:2px solid rgba(79,70,229,.15);border-top-color:var(--pc-primary);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>