<template>
  <div class="portal-page portal-appointment-book">
    <header class="pc-page-header"><div><h1 class="pc-page-title">Reservar una cita</h1><p class="pc-page-sub">Cuéntanos qué necesitas y cuándo te conviene; te confirmaremos en breve.</p></div><router-link to="/appointments" class="pc-link-back">&larr; Volver a citas</router-link></header>
    <form class="pc-card pc-form" @submit.prevent="submit">
      <div class="pc-form-row"><label>Servicio / Artículo <span class="pc-required">*</span></label><input v-model="form.service_item" type="text" required maxlength="190" placeholder="Ej.: cambio de pantalla de iPhone 13"></div>
      <div class="pc-form-grid"><div class="pc-form-row"><label>Tipo</label><select v-model="form.job_type"><option value="service">Servicio</option><option value="repair">Reparación</option><option value="installation">Instalación</option><option value="consultation">Consulta</option></select></div><div class="pc-form-row"><label>Fecha y hora preferidas <span class="pc-required">*</span></label><input v-model="form.scheduled_date" type="datetime-local" required></div></div>
      <div class="pc-form-grid"><div class="pc-form-row"><label>Marca del dispositivo <span class="pc-muted">(opcional)</span></label><input v-model="form.device_brand" type="text" maxlength="120"></div><div class="pc-form-row"><label>Modelo del dispositivo <span class="pc-muted">(opcional)</span></label><input v-model="form.device_model" type="text" maxlength="120"></div></div>
      <div class="pc-form-row"><label>Serie / IMEI <span class="pc-muted">(opcional)</span></label><input v-model="form.device_serial" type="text" maxlength="120"></div>
      <div class="pc-form-row"><label>¿Cuál es el problema o qué servicio necesitas?</label><textarea v-model="form.reported_issue" rows="4" maxlength="5000" placeholder="Describe el problema o servicio que necesitas"></textarea></div>
      <div v-if="error" class="pc-alert pc-alert-error">{{ error }}</div>
      <div class="pc-form-actions"><router-link to="/appointments" class="pc-btn pc-btn-ghost">Cancelar</router-link><button type="submit" class="pc-btn pc-btn-primary" :disabled="submitting"><span v-if="submitting">Enviando...</span><span v-else>Reservar cita</span></button></div>
    </form>
  </div>
</template>
<script>export default{data(){return{form:{service_item:'',job_type:'service',scheduled_date:'',device_brand:'',device_model:'',device_serial:'',reported_issue:''},submitting:false,error:''}},methods:{async submit(){if(!this.form.service_item||!this.form.scheduled_date){this.error='Completa los campos obligatorios.';return}this.error='';this.submitting=true;try{await axios.post('/portal/appointments',{service_item:this.form.service_item,job_type:this.form.job_type||undefined,scheduled_date:this.form.scheduled_date,reported_issue:this.form.reported_issue||undefined,device_brand:this.form.device_brand||undefined,device_model:this.form.device_model||undefined,device_serial:this.form.device_serial||undefined});this.$router.push('/appointments')}catch(e){this.error=e?.response?.data?.message||'No se pudo reservar la cita. Inténtalo de nuevo.'}this.submitting=false}}}</script>
<style scoped>.portal-appointment-book{padding-bottom:1rem}.pc-page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap}.pc-page-title{font-size:1.5rem;font-weight:700;margin:0}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:.2rem 0 0}.pc-link-back{color:var(--pc-text-muted);text-decoration:none}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius)}.pc-form{padding:1.5rem;display:flex;flex-direction:column;gap:1.15rem}.pc-form-grid{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.pc-form-row{display:flex;flex-direction:column;gap:.45rem}.pc-form-row label{font-size:.85rem;font-weight:600}.pc-muted{color:var(--pc-text-soft);font-weight:400}.pc-required{color:var(--pc-danger)}.pc-form-row input,.pc-form-row select,.pc-form-row textarea{width:100%;padding:.6rem .85rem;border:1px solid var(--pc-border-strong);border-radius:10px;background:var(--pc-surface-alt);box-sizing:border-box;font-family:inherit}.pc-form-actions{display:flex;justify-content:flex-end;gap:.6rem}.pc-btn{padding:.55rem 1rem;border-radius:10px;text-decoration:none;border:1px solid transparent}.pc-btn-primary{background:var(--pc-primary);color:#fff}.pc-btn-ghost{border-color:var(--pc-border-strong);color:var(--pc-text)}.pc-alert-error{padding:.7rem .95rem;border-radius:10px;background:#fef2f2;color:#b91c1c}@media(max-width:600px){.pc-form-grid{grid-template-columns:1fr}}</style>