<template>
  <div class="portal-page portal-article">
    <header class="pc-page-header"><router-link to="/help" class="pc-link-back">&larr; Volver al centro de ayuda</router-link></header>
    <div v-if="loading" class="pc-inline-loading"><div class="pc-spinner"></div><span>Cargando artículo...</span></div>
    <article v-else-if="article.id" class="pc-card pc-article-body"><div v-if="article.group" class="pc-article-crumb">{{ article.group.name }}</div><h1 class="pc-article-h1">{{ article.title }}</h1><div v-if="article.updated_at" class="pc-article-meta">Actualizado {{ formatDate(article.updated_at) }}</div><div class="pc-article-content" v-html="article.content || ''"></div></article>
    <div v-else class="pc-card pc-empty"><p>Artículo no encontrado</p></div>
  </div>
</template>
<script>export default{data(){return{article:{},loading:false}},watch:{'$route.params.slug':{handler(){this.fetch()},immediate:false}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;try{const{data}=await axios.get(`/portal/knowledge-base/${this.$route.params.slug}`);this.article=data||{}}catch(_){this.article={}}this.loading=false},formatDate(iso){if(!iso)return'';try{return new Date(iso).toLocaleDateString('es-HN')}catch(_){return iso}}}}</script>
<style scoped>.portal-article{padding-bottom:1rem}.pc-page-header{margin-bottom:1rem}.pc-link-back{color:var(--pc-text-muted);text-decoration:none}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius)}.pc-article-body{padding:2rem;max-width:820px;margin:auto}.pc-article-crumb{font-size:.78rem;font-weight:600;color:var(--pc-primary);text-transform:uppercase}.pc-article-h1{font-size:1.85rem;margin:.5rem 0}.pc-article-meta{color:var(--pc-text-soft);margin-bottom:1.5rem}.pc-article-content{line-height:1.7}.pc-article-content >>> img{max-width:100%;height:auto}.pc-inline-loading,.pc-empty{padding:3rem;text-align:center;color:var(--pc-text-muted)}.pc-spinner{width:28px;height:28px;border:2px solid rgba(79,70,229,.15);border-top-color:var(--pc-primary);border-radius:50%;animation:spin .7s linear infinite;margin:auto}@keyframes spin{to{transform:rotate(360deg)}}@media(max-width:768px){.pc-article-body{padding:1.25rem}.pc-article-h1{font-size:1.4rem}}</style>