<template>
  <div class="portal-page portal-contract-detail">
    <header class="pc-page-header"><div><h1 class="pc-page-title">{{ contract.contract_number || 'Contrato' }}</h1><p class="pc-page-sub" v-if="contract.subject">{{ contract.subject }}</p></div><router-link to="/contracts" class="pc-link-back">&larr; Volver</router-link></header>
    <div v-if="loading" class="pc-inline-loading"><div class="pc-spinner"></div><span>Cargando...</span></div>
    <div v-else class="pc-card pc-detail">
      <div class="pc-detail-header"><span :class="'pc-badge pc-badge-' + badgeClass(contract.status)">{{ statusLabel(contract.status) }}</span><div class="pc-amount" v-if="contract.value">{{ formatMoney(contract.value) }}</div></div>
      <dl class="pc-meta-grid"><div><dt>Tipo</dt><dd>{{ contract.type || '—' }}</dd></div><div><dt>Fecha de inicio</dt><dd>{{ contract.start_date || '—' }}</dd></div><div><dt>Fecha de finalización</dt><dd>{{ contract.end_date || '—' }}</dd></div><div><dt>Firma</dt><dd>{{ contract.signed_at ? formatDate(contract.signed_at) : 'No firmado' }}</dd></div><div v-if="contract.signer_name"><dt>Firmante</dt><dd>{{ contract.signer_name }}</dd></div></dl>
      <div v-if="contract.description" class="pc-block"><h3>Descripción</h3><div class="pc-html" v-html="contract.description"></div></div>
      <div v-if="contract.attachments && contract.attachments.length" class="pc-block"><h3>Archivos adjuntos</h3><ul class="pc-attachments"><li v-for="a in contract.attachments" :key="a.id" class="pc-attachment"><span class="pc-attachment-icon">📎</span><span class="pc-attachment-name">{{ a.file_name }}</span><a :href="downloadUrl(a.id)" target="_blank" rel="noopener" class="pc-chip">Descargar</a></li></ul></div>
    </div>
  </div>
</template>
<script>export default{data(){return{contract:{},loading:false}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;try{const{data}=await axios.get(`/portal/contracts/${this.$route.params.id}`);this.contract=data||{}}catch(_){}this.loading=false},downloadUrl(id){return `/api/portal/contracts/${this.$route.params.id}/attachments/${id}/download`},formatMoney(n){if(n==null)return'—';return Number(n).toLocaleString('es-HN',{minimumFractionDigits:2,maximumFractionDigits:2})},formatDate(iso){if(!iso)return'—';try{return new Date(iso).toLocaleString('es-HN')}catch(_){return iso}},badgeClass(s){const v=(s||'').toLowerCase();if(v==='active'||v==='signed')return'paid';if(v==='draft'||v==='pending')return'pending';if(['expired','cancelled','terminated'].includes(v))return'partial';return'pending'},statusLabel(s){const v=(s||'').toLowerCase();return {active:'Activo',signed:'Firmado',draft:'Borrador',pending:'Pendiente',expired:'Vencido',cancelled:'Cancelado',terminated:'Finalizado'}[v]||s||'—'}}}</script>
<style scoped>.portal-contract-detail{padding-bottom:1rem}.pc-page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap}.pc-page-title{font-size:1.5rem;font-weight:700;color:var(--pc-text);margin:0 0 .2rem}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:0}.pc-link-back{color:var(--pc-text-muted);text-decoration:none;font-size:.88rem}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius);box-shadow:var(--pc-shadow-sm);padding:1.5rem}.pc-detail-header{display:flex;justify-content:space-between;align-items:center;padding-bottom:1rem;border-bottom:1px solid var(--pc-border);margin-bottom:1.1rem}.pc-amount{font-size:1.4rem;font-weight:700}.pc-badge{display:inline-block;padding:.3rem .7rem;border-radius:999px;font-size:.78rem;font-weight:600}.pc-badge-paid{background:var(--pc-success-bg);color:var(--pc-success)}.pc-badge-pending{background:var(--pc-warning-bg);color:var(--pc-warning)}.pc-badge-partial{background:#fee2e2;color:#b91c1c}.pc-meta-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:.85rem 1.5rem;margin:0 0 1.2rem}.pc-meta-grid div{display:flex;flex-direction:column}.pc-meta-grid dt{font-size:.72rem;text-transform:uppercase;color:var(--pc-text-soft);font-weight:600}.pc-meta-grid dd{margin:.15rem 0 0}.pc-block{margin-top:1rem}.pc-block h3{font-size:.95rem;margin:0 0 .55rem}.pc-html{padding:.85rem 1rem;background:var(--pc-surface-alt);border-radius:10px;line-height:1.55}.pc-attachments{list-style:none;margin:0;padding:0}.pc-attachment{display:flex;align-items:center;gap:.7rem;padding:.55rem .85rem;border:1px solid var(--pc-border);border-radius:10px;margin-bottom:.45rem}.pc-attachment-name{flex:1}.pc-chip{padding:.3rem .75rem;border:1px solid var(--pc-border-strong);border-radius:6px;color:var(--pc-primary);text-decoration:none}.pc-inline-loading{display:flex;align-items:center;justify-content:center;gap:.75rem;padding:3rem}.pc-spinner{width:28px;height:28px;border:2px solid rgba(79,70,229,.15);border-top-color:var(--pc-primary);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>