<template>
  <div class="portal-page portal-invoices">
    <header class="pc-page-header"><div><h1 class="pc-page-title">Facturas</h1><p class="pc-page-sub">Consulta y descarga tus facturas</p></div></header>
    <div class="pc-card">
      <div class="pc-toolbar"><div class="pc-search"><input v-model="search" type="text" placeholder="Buscar por referencia o fecha..." @input="debounceFetch" /></div></div>
      <div v-if="loading" class="pc-inline-loading"><div class="pc-spinner"></div><span>Cargando facturas...</span></div>
      <template v-else>
        <div v-if="!invoices.length" class="pc-empty"><p>No se encontraron facturas</p></div>
        <div v-else class="pc-table-wrap pc-hide-mobile"><table class="pc-table"><thead><tr><th>Referencia</th><th>Fecha</th><th>Total</th><th>Pagado</th><th>Pendiente</th><th>Estado</th><th></th></tr></thead><tbody><tr v-for="inv in invoices" :key="inv.id"><td><router-link :to="`/invoices/${inv.id}`" class="pc-link">{{ inv.Ref }}</router-link></td><td>{{ inv.date }}</td><td>{{ formatMoney(inv.GrandTotal) }}</td><td>{{ formatMoney(inv.paid_amount) }}</td><td>{{ formatMoney(inv.due) }}</td><td><span :class="'pc-badge pc-badge-' + badgeClass(inv.payment_status)">{{ statusLabel(inv.payment_status) }}</span></td><td><a :href="`/api/portal/invoices/${inv.id}/pdf`" target="_blank" rel="noopener" class="pc-chip">PDF</a></td></tr></tbody></table></div>
        <ul v-if="invoices.length" class="pc-mobile-list pc-show-mobile"><li v-for="inv in invoices" :key="'m-' + inv.id" class="pc-mobile-row"><router-link :to="`/invoices/${inv.id}`" class="pc-mobile-row-main"><div class="pc-mobile-top"><strong>{{ inv.Ref }}</strong><span :class="'pc-badge pc-badge-' + badgeClass(inv.payment_status)">{{ statusLabel(inv.payment_status) }}</span></div><div>{{ inv.date }} · {{ formatMoney(inv.GrandTotal) }}</div><div class="pc-mobile-foot"><span>Pagado: {{ formatMoney(inv.paid_amount) }}</span><span>Pendiente: {{ formatMoney(inv.due) }}</span></div></router-link></li></ul>
        <div v-if="totalRows > pageSize" class="pc-pagination"><button type="button" class="pc-pg-btn" :disabled="page <= 1" @click="page--; fetch()">Anterior</button><span class="pc-pg-info">Página {{ page }} de {{ totalPages }}</span><button type="button" class="pc-pg-btn" :disabled="page >= totalPages" @click="page++; fetch()">Siguiente</button></div>
      </template>
    </div>
  </div>
</template>
<script>
export default { data(){return{invoices:[],search:'',page:1,pageSize:10,totalRows:0,loading:false,debounce:null}},computed:{totalPages(){return Math.ceil(this.totalRows/this.pageSize)||1}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;try{const{data}=await axios.get('/portal/invoices',{params:{page:this.page,limit:this.pageSize,search:this.search||undefined}});this.invoices=data.invoices||[];this.totalRows=data.totalRows||0}catch(_){}this.loading=false},debounceFetch(){clearTimeout(this.debounce);this.debounce=setTimeout(()=>{this.page=1;this.fetch()},300)},formatMoney(n){if(n==null)return'0.00';return Number(n).toLocaleString('es-HN',{minimumFractionDigits:2,maximumFractionDigits:2})},badgeClass(s){const v=(s||'').toLowerCase();if(v==='paid'||v==='completed')return'paid';if(v==='partial')return'partial';return'pending'},statusLabel(s){const v=(s||'').toLowerCase();return {paid:'Pagado',completed:'Completado',partial:'Parcial',pending:'Pendiente',unpaid:'Sin pagar'}[v]||s||'Pendiente'}}}
</script>
<style scoped>
.portal-invoices{padding-bottom:1rem}.pc-page-header{margin-bottom:1.25rem}.pc-page-title{font-size:1.5rem;font-weight:700;margin:0 0 .2rem}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:0}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius);overflow:hidden}.pc-toolbar{padding:.9rem 1.15rem;border-bottom:1px solid var(--pc-border)}.pc-search input{width:100%;padding:.6rem 1rem;border:1px solid var(--pc-border-strong);border-radius:10px;box-sizing:border-box}.pc-inline-loading,.pc-empty{padding:3rem;text-align:center;color:var(--pc-text-muted)}.pc-spinner{width:28px;height:28px;border:2px solid rgba(79,70,229,.15);border-top-color:var(--pc-primary);border-radius:50%;animation:spin .7s linear infinite;margin:0 auto .5rem}@keyframes spin{to{transform:rotate(360deg)}}.pc-table-wrap{overflow-x:auto}.pc-table{width:100%;border-collapse:collapse;font-size:.88rem}.pc-table th,.pc-table td{padding:.7rem 1.15rem;text-align:left;border-bottom:1px solid var(--pc-border)}.pc-table th{background:var(--pc-surface-alt);font-weight:600}.pc-link{color:var(--pc-primary)}.pc-chip{padding:.25rem .6rem;border:1px solid var(--pc-border-strong);border-radius:6px}.pc-badge{display:inline-block;padding:.22rem .55rem;border-radius:999px;font-size:.72rem;font-weight:600}.pc-badge-paid{background:var(--pc-success-bg);color:var(--pc-success)}.pc-badge-pending,.pc-badge-unpaid{background:var(--pc-warning-bg);color:var(--pc-warning)}.pc-badge-partial{background:#dbeafe;color:#1d4ed8}.pc-mobile-list{list-style:none;margin:0;padding:0}.pc-mobile-row{border-bottom:1px solid var(--pc-border)}.pc-mobile-row-main{display:block;padding:.95rem 1.15rem;color:var(--pc-text);text-decoration:none}.pc-mobile-top,.pc-mobile-foot{display:flex;justify-content:space-between;gap:.5rem;margin-bottom:.35rem}.pc-pagination{display:flex;align-items:center;justify-content:center;gap:1rem;padding:.85rem}.pc-pg-btn{padding:.5rem 1rem;border:1px solid var(--pc-border-strong);border-radius:8px;background:var(--pc-surface)}.pc-show-mobile{display:none}@media(max-width:768px){.pc-show-mobile{display:block}.pc-hide-mobile{display:none}.pc-pagination{flex-wrap:wrap}}
</style>