<template>
  <div class="portal-page portal-payments">
    <header class="pc-page-header"><div><h1 class="pc-page-title">Pagos</h1><p class="pc-page-sub">Historial de tus pagos</p></div></header>
    <div class="pc-card"><div class="pc-toolbar"><input v-model="search" class="pc-search-input" type="text" placeholder="Buscar por referencia, fecha o método..." @input="debounceFetch"></div>
      <div v-if="loading" class="pc-state">Cargando pagos...</div><template v-else><div v-if="!payments.length" class="pc-state">No se encontraron pagos</div>
      <div v-else class="pc-table-wrap"><table class="pc-table"><thead><tr><th>Fecha</th><th>Referencia</th><th>Factura</th><th>Método</th><th>Importe</th></tr></thead><tbody><tr v-for="(pmt,i) in payments" :key="i"><td>{{pmt.date}}</td><td>{{pmt.Ref}}</td><td>{{pmt.Sale_Ref||'—'}}</td><td>{{ methodLabel(pmt.payment_method) }}</td><td>{{formatMoney(pmt.montant)}}</td></tr></tbody></table></div>
      <div v-if="totalRows>pageSize" class="pc-pagination"><button :disabled="page<=1" @click="page--;fetch()">Anterior</button><span>Página {{page}} de {{totalPages}}</span><button :disabled="page>=totalPages" @click="page++;fetch()">Siguiente</button></div></template>
    </div>
  </div>
</template>
<script>
export default{data(){return{payments:[],search:'',page:1,pageSize:10,totalRows:0,loading:false,debounce:null}},computed:{totalPages(){return Math.ceil(this.totalRows/this.pageSize)||1}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;try{const{data}=await axios.get('/portal/payments',{params:{page:this.page,limit:this.pageSize,search:this.search||undefined}});this.payments=data.payments||[];this.totalRows=data.totalRows||0}catch(_){}this.loading=false},debounceFetch(){clearTimeout(this.debounce);this.debounce=setTimeout(()=>{this.page=1;this.fetch()},300)},formatMoney(n){return Number(n||0).toLocaleString('es-HN',{minimumFractionDigits:2,maximumFractionDigits:2})},methodLabel(v){const s=(v||'').toLowerCase();return {cash:'Efectivo',cheque:'Cheque',credit_card:'Tarjeta de crédito',bank_transfer:'Transferencia bancaria',other:'Otro'}[s]||v||'—'}}}
</script>
<style scoped>.portal-payments{padding-bottom:1rem}.pc-page-header{margin-bottom:1.25rem}.pc-page-title{font-size:1.5rem;font-weight:700;margin:0}.pc-page-sub{color:var(--pc-text-muted);margin:.2rem 0 0}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius);overflow:hidden}.pc-toolbar{padding:1rem}.pc-search-input{width:100%;padding:.65rem;border:1px solid var(--pc-border-strong);border-radius:10px;box-sizing:border-box}.pc-state{padding:3rem;text-align:center;color:var(--pc-text-muted)}.pc-table-wrap{overflow-x:auto}.pc-table{width:100%;border-collapse:collapse}.pc-table th,.pc-table td{padding:.75rem 1rem;border-bottom:1px solid var(--pc-border);text-align:left}.pc-table th{background:var(--pc-surface-alt)}.pc-pagination{display:flex;justify-content:center;align-items:center;gap:1rem;padding:1rem}.pc-pagination button{padding:.5rem 1rem;border:1px solid var(--pc-border-strong);border-radius:8px;background:var(--pc-surface)}</style>