<template>
  <div class="portal-page portal-quotation-request">
    <header class="pc-page-header"><div><h1 class="pc-page-title">Solicitar una cotización</h1><p class="pc-page-sub">Cuéntanos qué necesitas y nuestro equipo te responderá en breve.</p></div><router-link to="/quotations" class="pc-link-back">&larr; Volver a cotizaciones</router-link></header>
    <form class="pc-card pc-form" @submit.prevent="submit">
      <div class="pc-form-row"><label>Asunto <span class="pc-muted">(opcional)</span></label><input v-model="form.subject" type="text" maxlength="190" placeholder="Ej.: mobiliario para nueva sucursal"></div>
      <div class="pc-form-row"><label>Detalles <span class="pc-required">*</span></label><textarea v-model="form.notes" rows="5" required maxlength="5000" placeholder="Describe qué necesitas, fecha estimada, lugar de entrega, etc."></textarea></div>
      <div class="pc-form-row"><label>Artículos <span class="pc-muted">(opcional)</span></label><div v-for="(item,i) in form.items" :key="i" class="pc-item-row"><input v-model="item.description" type="text" placeholder="Descripción del artículo"><input v-model.number="item.quantity" type="number" min="0" step="0.01" placeholder="Cant." class="pc-qty-input"><button type="button" class="pc-icon-btn" @click="removeItem(i)" title="Eliminar">×</button></div><button type="button" class="pc-btn pc-btn-ghost" @click="addItem">+ Agregar artículo</button></div>
      <div v-if="error" class="pc-alert pc-alert-error">{{error}}</div><div class="pc-form-actions"><router-link to="/quotations" class="pc-btn pc-btn-ghost">Cancelar</router-link><button type="submit" class="pc-btn pc-btn-primary" :disabled="submitting"><span v-if="submitting">Enviando...</span><span v-else>Enviar solicitud</span></button></div>
    </form>
  </div>
</template>
<script>export default{data(){return{form:{subject:'',notes:'',items:[{description:'',quantity:1}]},submitting:false,error:''}},methods:{addItem(){this.form.items.push({description:'',quantity:1})},removeItem(i){this.form.items.splice(i,1)},async submit(){if(!this.form.notes||!this.form.notes.trim()){this.error='Describe tu solicitud.';return}this.error='';this.submitting=true;try{const items=this.form.items.filter(it=>it.description&&it.description.trim());await axios.post('/portal/quotations',{subject:this.form.subject||undefined,notes:this.form.notes,items:items.length?items:undefined});this.$router.push('/quotations')}catch(e){this.error=e?.response?.data?.message||'No se pudo enviar tu solicitud. Inténtalo de nuevo.'}this.submitting=false}}}</script>
<style scoped>.portal-quotation-request{padding-bottom:1rem}.pc-page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap}.pc-page-title{font-size:1.5rem;font-weight:700;margin:0}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:.2rem 0 0}.pc-link-back{color:var(--pc-text-muted);text-decoration:none}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius)}.pc-form{padding:1.5rem;display:flex;flex-direction:column;gap:1.15rem}.pc-form-row{display:flex;flex-direction:column;gap:.45rem}.pc-form-row label{font-size:.85rem;font-weight:600}.pc-muted{color:var(--pc-text-soft);font-weight:400}.pc-required{color:var(--pc-danger)}.pc-form-row input,.pc-form-row textarea{width:100%;padding:.6rem .85rem;border:1px solid var(--pc-border-strong);border-radius:10px;background:var(--pc-surface-alt);box-sizing:border-box;font-family:inherit}.pc-item-row{display:flex;gap:.5rem;margin-bottom:.5rem;align-items:center}.pc-item-row input{flex:1}.pc-qty-input{max-width:110px}.pc-icon-btn{width:38px;height:38px;border:1px solid var(--pc-border-strong);border-radius:10px;background:transparent}.pc-btn{display:inline-flex;align-items:center;padding:.55rem 1rem;border-radius:10px;text-decoration:none;border:1px solid transparent}.pc-btn-primary{background:var(--pc-primary);color:#fff}.pc-btn-ghost{border-color:var(--pc-border-strong);color:var(--pc-text)}.pc-form-actions{display:flex;justify-content:flex-end;gap:.6rem}.pc-alert-error{padding:.7rem .95rem;border-radius:10px;background:#fef2f2;color:#b91c1c}</style>