<template>
  <div class="portal-page portal-quotation-detail">
    <header class="pc-page-header">
      <div><h1 class="pc-page-title">Cotización {{ quotation.Ref || '' }}</h1><p class="pc-page-sub" v-if="quotation.date">Creada el {{ quotation.date }}</p></div>
      <router-link to="/quotations" class="pc-link-back">&larr; Volver a cotizaciones</router-link>
    </header>
    <div v-if="loading" class="pc-inline-loading"><div class="pc-spinner"></div><span>Cargando...</span></div>
    <div v-else class="pc-card pc-detail">
      <div class="pc-detail-header"><span :class="'pc-badge pc-badge-' + badgeClass(quotation.statut)">{{ statusLabel(quotation.statut) }}</span><div class="pc-grand">{{ formatMoney(quotation.GrandTotal) }}</div></div>
      <dl class="pc-meta-grid"><div><dt>Almacén</dt><dd>{{ quotation.warehouse_name || '—' }}</dd></div><div><dt>Descuento</dt><dd>{{ formatMoney(quotation.discount) }}</dd></div><div><dt>Envío</dt><dd>{{ formatMoney(quotation.shipping) }}</dd></div><div><dt>Impuesto</dt><dd>{{ formatMoney(quotation.TaxNet) }} ({{ quotation.tax_rate || 0 }}%)</dd></div></dl>
      <div v-if="quotation.notes" class="pc-notes"><h3>Notas</h3><pre>{{ quotation.notes }}</pre></div>
      <div v-if="quotation.details && quotation.details.length" class="pc-table-wrap"><h3>Artículos</h3><table class="pc-table"><thead><tr><th>Producto</th><th>Cantidad</th><th>Precio</th><th>Total</th></tr></thead><tbody><tr v-for="(d, i) in quotation.details" :key="i"><td>{{ d.product_name || '—' }}</td><td>{{ d.quantity }}</td><td>{{ formatMoney(d.price) }}</td><td>{{ formatMoney(d.total) }}</td></tr></tbody></table></div>
    </div>
  </div>
</template>
<script>export default{data(){return{quotation:{},loading:false}},mounted(){this.fetch()},methods:{async fetch(){this.loading=true;try{const{data}=await axios.get(`/portal/quotations/${this.$route.params.id}`);this.quotation=data||{}}catch(_){}this.loading=false},formatMoney(n){if(n==null)return'0.00';return Number(n).toLocaleString('es-HN',{minimumFractionDigits:2,maximumFractionDigits:2})},badgeClass(s){const v=(s||'').toLowerCase();if(['approved','accepted','completed'].includes(v))return'paid';if(['pending','requested'].includes(v))return'pending';if(['rejected','cancelled'].includes(v))return'partial';return'pending'},statusLabel(s){const v=(s||'').toLowerCase();return {approved:'Aprobada',accepted:'Aceptada',completed:'Completada',pending:'Pendiente',requested:'Solicitada',rejected:'Rechazada',cancelled:'Cancelada'}[v]||s||'Pendiente'}}}</script>
<style scoped>.portal-quotation-detail{padding-bottom:1rem}.pc-page-header{display:flex;align-items:center;justify-content:space-between;margin-bottom:1.25rem;gap:1rem;flex-wrap:wrap}.pc-page-title{font-size:1.5rem;font-weight:700;color:var(--pc-text);margin:0 0 .2rem}.pc-page-sub{font-size:.9rem;color:var(--pc-text-muted);margin:0}.pc-link-back{color:var(--pc-text-muted);text-decoration:none;font-size:.88rem}.pc-card{background:var(--pc-surface);border:1px solid var(--pc-border);border-radius:var(--pc-radius);box-shadow:var(--pc-shadow-sm);padding:1.5rem}.pc-detail-header{display:flex;justify-content:space-between;align-items:center;padding-bottom:1rem;border-bottom:1px solid var(--pc-border);margin-bottom:1.1rem}.pc-grand{font-size:1.5rem;font-weight:700}.pc-badge{padding:.3rem .7rem;border-radius:999px;font-size:.78rem;font-weight:600}.pc-badge-paid{background:var(--pc-success-bg);color:var(--pc-success)}.pc-badge-pending{background:var(--pc-warning-bg);color:var(--pc-warning)}.pc-badge-partial{background:#fee2e2;color:#b91c1c}.pc-meta-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:.85rem 1.5rem;margin:0 0 1.2rem}.pc-meta-grid div{display:flex;flex-direction:column}.pc-meta-grid dt{font-size:.72rem;text-transform:uppercase;color:var(--pc-text-soft);font-weight:600}.pc-meta-grid dd{margin:.15rem 0 0}.pc-notes h3,.pc-table-wrap h3{font-size:.95rem;margin:0 0 .55rem}.pc-notes pre{background:var(--pc-surface-alt);padding:.85rem 1rem;border-radius:10px;font-family:inherit;white-space:pre-wrap}.pc-table-wrap{overflow-x:auto}.pc-table{width:100%;border-collapse:collapse}.pc-table th,.pc-table td{padding:.6rem .75rem;text-align:left;border-bottom:1px solid var(--pc-border)}.pc-table th{background:var(--pc-surface-alt)}.pc-inline-loading{display:flex;align-items:center;justify-content:center;gap:.75rem;padding:3rem}.pc-spinner{width:28px;height:28px;border:2px solid rgba(79,70,229,.15);border-top-color:var(--pc-primary);border-radius:50%;animation:spin .7s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}</style>